### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by DavisMeee** [styvesg/nsd#2]
Thank you for your contributions!
I would like to know where I can find this '.pkl' file.

```
#import pandas as pd
nsd_stiminfo_file = '~/repo.data/datasets/nsd/dev/nsd_stim_info_merged.pkl'
stiminfo = pd.read_pickle(nsd_stiminfo_file) 
```

**Comment by DavisMeee** [comment]
Ohhh and also for these files, thank you so much!
```
annDir = '/home/styvesg/repo.data/datasets/coco/'
imgDir = annDir + 'panoptic_annotations_trainval2017/annotations/panoptic/' # combined folder with train2017 and val2017 png masks
panop_trn_annFile = annDir + 'panoptic_annotations_trainval2017/annotations/panoptic_train2017.json'
panop_val_annFile = annDir + 'panoptic_annotations_trainval2017/annotations/panoptic_val2017.json'
```

**Comment by styvesg** [comment]
I believe 'dev/nsd_stim_info_merged.pkl' must have been from an earlier stage of the NSD project development and the information it contained has been moved to a different file in the release version. I'll add this small file to my repo though it would be probably best to implement a workaround that works with the official release.
As for the other files, they are from the download of COCO panoptic annotations. However, I would caution against using any if this code since it was development ideas for a different project which is not used in this project (I should have cleaned the notebook) and it contains numerous errors.
